update

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -85,15 +85,22 @@ jobs:
 
     - name: Show generated packages
       run: |
-        find sdk/bin/packages -name "*.ipk"
+        find sdk/bin/packages \( -name "*.ipk" -o -name "*.apk" \)
 
     - name: Prepare Release
       run: |
         mkdir -p release
-        IPK=$(find sdk/bin/packages -name "*.ipk" | head -n1)
-        FILE=$(basename "$IPK")
-        ARCH=$(echo "$FILE" | sed -E 's/^.*_[0-9]+\.[0-9]+\.[0-9]+-r[0-9]+_(.*)\.ipk$/\1/')
-        cp "$IPK" "release/badvpn-tun2socks_${ARCH}.ipk"
+
+        PKG=$(find sdk/bin/packages \( -name "*.ipk" -o -name "*.apk" \) | head -n1)
+
+        if [ -z "$PKG" ]; then
+        echo "Package not found!"
+        find sdk/bin/packages
+        exit 1
+        fi
+
+        cp "$PKG" release/
+
         ls -lh release
 
     - name: Upload build logs
